# Generated by Django 4.2.2 on 2023-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('urlImg', models.TextField(verbose_name='URL_Ссылка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
            ],
        ),
    ]
